dev@SkyCrypt:~/config/nginx/conf.d$ cat skycrypt-test.conf 
upstream cupcake {
    server 192.168.0.13:3000 weight=5;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    gzip on;
    gzip_vary on;

    server_name cupcake.shiiyu.moe;

    ssl_certificate /etc/letsencrypt/live/shiiyu.moe/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shiiyu.moe/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    #   vhost_traffic_status_filter_by_set_key $site_section section::$server_name;

    location =/ {
        limit_conn limit_main 3;

        proxy_cache cache_main;
        proxy_cache_key $proxy_host$request_uri$cookie_favorite;
        proxy_cache_valid 200 10m;

        proxy_pass http://cupcake;
    }

    location /stats {
        limit_req zone=limit_v2_stats burst=9 delay=16;
        limit_conn limit_main 2;

        proxy_cache cache_main;
        proxy_cache_key $proxy_host$request_uri$cookie_disabledPacks;
        proxy_cache_valid 200 5m;

        proxy_pass http://cupcake;
    }

    location ~* ^\/api\/(uuid) {
        limit_req zone=limit_v2_uuid burst=12 delay=24;

        proxy_cache cache_main;
        proxy_cache_valid 200 60m;

        proxy_pass http://cupcake;
    } 

    location ~* ^\/api\/garden\/([^/]+) {
        limit_req zone=limit_v2_garden burst=12 delay=24;

        proxy_cache cache_main;
        proxy_cache_valid 200 60m;

        proxy_pass http://cupcake;
    }

    location ~* ^\/api\/(item) {
        limit_req zone=limit_assets burst=125 delay=125;

        proxy_cache cache_main;
        proxy_cache_key $proxy_host$request_uri$cookie_disabledPacks;
        proxy_cache_valid 200 180m;

        proxy_pass http://cupcake;
    }

    location ~* ^\/api\/(head|leather|potion|themes) {
        limit_req zone=limit_assets burst=125 delay=125;

        proxy_cache cache_main;
        proxy_cache_valid 200 180m;

        proxy_pass http://cupcake;
    }

    location ~* ^\/(\_app|img) {
        limit_req zone=limit_assets burst=125 delay=125;

        proxy_cache cache_main;
        proxy_cache_valid 200 180m;

        proxy_pass http://cupcake;
    }

    location /manifest.webmanifest {
        limit_conn limit_main 3;

        proxy_cache cache_main;
        proxy_cache_key $proxy_host$request_uri$cookie_favorite;
        proxy_cache_valid 200 360m;

        proxy_pass http://cupcake;
    }

    location /api {
        deny all;

        proxy_pass http://cupcake;
    }

    location / {
        limit_conn limit_main 4;

        proxy_cache cache_main;
        proxy_cache_valid 200 5m;

        proxy_pass http://cupcake;
    }

    error_page 404 500 502 503 504 /offline.html;
    location = /offline.html {
        root /usr/share/nginx/html;
        internal;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name cupcake.shiiyu.moe;

    if ($request_uri ~* "%0A|%0D") {
        return 400;
    }

    return 308 https://$host$request_uri;
}