/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * SkyCrypt API
 * API for SkyCrypt - A Hypixel SkyBlock Stats Viewer
 * OpenAPI spec version: 1.0
 */
import * as zod from "zod";

/**
 * Returns accessories for the given user and profile ID
 * @summary Get accessories stats of a specified player
 */
export const GetApiAccessoriesUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiAccessoriesUuidProfileIdResponse = zod.unknown();

/**
 * Returns bestiary for the given user and profile ID
 * @summary Get bestiary stats of a specified player
 */
export const GetApiBestiaryUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiBestiaryUuidProfileIdResponse = zod.unknown();

/**
 * Returns collections for the given user and profile ID
 * @summary Get collections stats of a specified player
 */
export const GetApiCollectionsUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiCollectionsUuidProfileIdResponse = zod.unknown();

/**
 * Returns Crimson Isle stats for the given user and profile ID
 * @summary Get Crimson Isle stats of a specified player
 */
export const GetApiCrimsonIsleUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiCrimsonIsleUuidProfileIdResponse = zod.unknown();

/**
 * Returns dungeons for the given user and profile ID
 * @summary Get dungeons stats of a specified player
 */
export const GetApiDungeonsUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiDungeonsUuidProfileIdResponse = zod.unknown();

/**
 * Returns embed data for the given user (UUID or username) and optional profile ID
 * @summary Get embed data for a specified player
 */
export const GetApiEmbedUuidParams = zod.object({
  uuid: zod.string().describe("User UUID or username")
});

export const GetApiEmbedUuidQueryParams = zod.object({
  profileId: zod.string().optional().describe("Profile ID (optional, defaults to selected profile)")
});

export const GetApiEmbedUuidResponse = zod.unknown();

/**
 * Retrieves all emojis from the database
 * @summary Get all emojis
 */
export const GetApiEmojisResponse = zod.record(zod.string(), zod.unknown());

/**
 * Returns garden data for the given profile ID
 * @summary Get garden stats of a specified profile
 */
export const GetApiGardenProfileIdParams = zod.object({
  profileId: zod.string().describe("Profile ID")
});

export const GetApiGardenProfileIdResponse = zod.unknown();

/**
 * Returns gear for the given user and profile ID
 * @summary Get gear stats of a specified player
 */
export const GetApiGearUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiGearUuidProfileIdResponse = zod.unknown();

/**
 * Returns a PNG image of a head for the given texture ID
 * @summary Render and return a head image
 */
export const GetApiHeadTextureIdParams = zod.object({
  textureId: zod.string().describe("Texture ID")
});

export const GetApiHeadTextureIdResponse = zod.file();

/**
 * Returns inventory items for the given user, profile ID, and inventory ID. Supports museum, search, and other inventories.
 * @summary Get inventory items for a specified player
 */
export const GetApiInventoryUuidProfileIdInventoryIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID"),
  inventoryId: zod.string().describe("Inventory ID (e.g., museum, search, or other inventory types)")
});

export const GetApiInventoryUuidProfileIdInventoryIdQueryParams = zod.object({
  query: zod.string().optional().describe("Search query (required when inventoryId is 'search')")
});

export const GetApiInventoryUuidProfileIdInventoryIdResponseItem = zod.unknown();
export const GetApiInventoryUuidProfileIdInventoryIdResponse = zod.array(GetApiInventoryUuidProfileIdInventoryIdResponseItem);

/**
 * Returns a PNG image of an item for the given texture ID
 * @summary Render and return an item image
 */
export const GetApiItemItemIdParams = zod.object({
  itemId: zod.string().describe("Item ID")
});

export const GetApiItemItemIdResponse = zod.file();

/**
 * Returns a PNG image of leather armor for the given type and color
 * @summary Render and return a leather armor image
 */
export const GetApiLeatherTypeColorParams = zod.object({
  type: zod.string().describe("Armor Type"),
  color: zod.string().describe("Armor Color")
});

export const GetApiLeatherTypeColorResponse = zod.file();

/**
 * Returns minions for the given user and profile ID
 * @summary Get minions stats of a specified player
 */
export const GetApiMinionsUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiMinionsUuidProfileIdResponse = zod.unknown();

/**
 * Returns misc stats for the given user and profile ID
 * @summary Get misc stats of a specified player
 */
export const GetApiMiscUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiMiscUuidProfileIdResponse = zod.unknown();

/**
 * Returns networth for the given user and profile ID
 * @summary Get networth of a specified player
 */
export const GetApiNetworthUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiNetworthUuidProfileIdResponse = zod.unknown();

/**
 * Returns pets for the given user and profile ID
 * @summary Get pets stats of a specified player
 */
export const GetApiPetsUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiPetsUuidProfileIdResponse = zod.unknown();

/**
 * Returns player stats for the given user and profile ID
 * @summary Get player stats of a specified player
 */
export const GetApiPlayerStatsUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiPlayerStatsUuidProfileIdResponse = zod.unknown();

/**
 * Returns a PNG image of a potion for the given type and color
 * @summary Render and return a potion image
 */
export const GetApiPotionTypeColorParams = zod.object({
  type: zod.string().describe("Potion Type"),
  color: zod.string().describe("Potion Color")
});

export const GetApiPotionTypeColorResponse = zod.file();

/**
 * Returns a list of resource packs
 * @summary Get list of resource packs
 */
export const GetApiResourcepacksResponseItem = zod.unknown();
export const GetApiResourcepacksResponse = zod.array(GetApiResourcepacksResponseItem);

/**
 * Returns rift data for the given user and profile ID
 * @summary Get rift stats of a specified player
 */
export const GetApiRiftUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiRiftUuidProfileIdResponse = zod.unknown();

/**
 * Returns skills for the given user and profile ID
 * @summary Get skills stats of a specified player
 */
export const GetApiSkillsUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiSkillsUuidProfileIdResponse = zod.unknown();

/**
 * Returns slayer statistics for the given user and profile ID
 * @summary Get slayer stats of a specified player
 */
export const GetApiSlayerUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiSlayerUuidProfileIdResponse = zod.unknown();

/**
 * Returns stats for the given user and profile ID
 * @summary Get stats of a specified player
 */
export const GetApiStatsUuidProfileIdParams = zod.object({
  uuid: zod.string().describe("User UUID"),
  profileId: zod.string().describe("Profile ID")
});

export const GetApiStatsUuidProfileIdResponse = zod.unknown();

/**
 * Returns the username associated with the given UUID
 * @summary Get username for a specified UUID
 */
export const GetApiUsernameUuidParams = zod.object({
  uuid: zod.string().describe("UUID")
});

export const GetApiUsernameUuidResponse = zod.unknown();

/**
 * Returns the UUID associated with the given username
 * @summary Get UUID for a specified username
 */
export const GetApiUuidUsernameParams = zod.object({
  username: zod.string().describe("Username")
});

export const GetApiUuidUsernameResponse = zod.unknown();
