/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * SkyCrypt API
 * API for SkyCrypt - A Hypixel SkyBlock Stats Viewer
 * OpenAPI spec version: 1.0
 */
import { customFetch } from "./mutator/custom-instance";
export interface FiberMap {
  [key: string]: unknown;
}

export type ModelsArmorResultStats = { [key: string]: number };

export interface ModelsSourceTab {
  icon?: string;
  name?: string;
}

export interface ModelsWikipediaLinks {
  fandom?: string;
  official?: string;
}

export interface ModelsStrippedItem {
  Count?: number;
  containsItems?: ModelsStrippedItem[];
  display_name?: string;
  isInactive?: boolean;
  lore?: string[];
  rarity?: string;
  recombobulated?: boolean;
  shiny?: boolean;
  source?: string;
  sourceTab?: ModelsSourceTab;
  texture_pack?: string;
  texture_path?: string;
  wiki?: ModelsWikipediaLinks;
}

export interface ModelsArmorResult {
  armor?: ModelsStrippedItem[];
  set_name?: string;
  set_rarity?: string;
  stats?: ModelsArmorResultStats;
}

export interface ModelsBestRunOutput {
  damage_dealt?: number;
  damage_mitigated?: number;
  deaths?: number;
  dungeon_class?: string;
  elapsed_time?: number;
  grade?: string;
  mobs_killed?: number;
  score_bonus?: number;
  score_exploration?: number;
  score_skill?: number;
  score_speed?: number;
  secrets_found?: number;
  timestamp?: number;
}

export interface ModelsBestiaryMobOutput {
  kills?: number;
  maxKills?: number;
  maxTier?: number;
  name?: string;
  nextTierKills?: number;
  texture?: string;
  tier?: number;
}

export interface ModelsBestiaryCategoryOutput {
  mobs?: ModelsBestiaryMobOutput[];
  mobsMaxed?: number;
  mobsUnlocked?: number;
  name?: string;
  texture?: string;
}

export type ModelsBestiaryOutputCategories = { [key: string]: ModelsBestiaryCategoryOutput };

export interface ModelsBestiaryOutput {
  categories?: ModelsBestiaryOutputCategories;
  familiesCompleted?: number;
  familiesUnlocked?: number;
  familyTiers?: number;
  level?: number;
  maxFamilyTiers?: number;
  maxLevel?: number;
  totalFamilies?: number;
}

export interface ModelsSkill {
  level?: number;
  levelCap?: number;
  levelWithProgress?: number;
  maxLevel?: number;
  maxed?: boolean;
  progress?: number;
  texture?: string;
  uncappedLevel?: number;
  unlockableLevelWithProgress?: number;
  xp?: number;
  xpCurrent?: number;
  xpForNext?: number;
}

export type ModelsClassDataClasses = { [key: string]: ModelsSkill };

export interface ModelsClassData {
  classAverage?: number;
  classAverageWithProgress?: number;
  classes?: ModelsClassDataClasses;
  selectedClass?: string;
  totalClassExp?: number;
}

export interface ModelsCollectionCategoryItemAmount {
  amount?: number;
  username?: string;
}

export interface ModelsCollectionCategoryItem {
  amount?: number;
  amounts?: ModelsCollectionCategoryItemAmount[];
  id?: string;
  maxTier?: number;
  name?: string;
  texture?: string;
  tier?: number;
  totalAmount?: number;
}

export interface ModelsCollectionCategory {
  items?: ModelsCollectionCategoryItem[];
  maxTiers?: number;
  name?: string;
  texture?: string;
  totalTiers?: number;
}

export type ModelsCollectionsOutputCategories = { [key: string]: ModelsCollectionCategory };

export interface ModelsCollectionsOutput {
  categories?: ModelsCollectionsOutputCategories;
  maxedCollections?: number;
  totalCollections?: number;
}

export interface ModelsCommissions {
  completions?: number;
  milestone?: number;
}

export type ModelsContestMedals = { [key: string]: number };

export interface ModelsContest {
  amount?: number;
  collected?: number;
  maxed?: boolean;
  medals?: ModelsContestMedals;
  name?: string;
  texture?: string;
}

export interface ModelsCorpse {
  amount?: number;
  name?: string;
  texture_path?: string;
}

export interface ModelsCorpses {
  corpses?: ModelsCorpse[];
  found?: number;
  max?: number;
}

export interface ModelsCrimsonIsleDojoChallenge {
  id?: string;
  name?: string;
  points?: number;
  rank?: string;
  texture?: string;
  time?: number;
}

export interface ModelsCrimsonIsleDojo {
  challenges?: ModelsCrimsonIsleDojoChallenge[];
  totalPoints?: number;
}

export interface ModelsCrimsonIsleFactions {
  barbariansReputation?: number;
  magesReputation?: number;
  selectedFaction?: string;
}

export interface ModelsCrimsonIsleKuudraTier {
  id?: string;
  kills?: number;
  name?: string;
  texture?: string;
}

export interface ModelsCrimsonIsleKuudra {
  tiers?: ModelsCrimsonIsleKuudraTier[];
  totalKills?: number;
}

export interface ModelsCrimsonIsleOutput {
  dojo?: ModelsCrimsonIsleDojo;
  factions?: ModelsCrimsonIsleFactions;
  kuudra?: ModelsCrimsonIsleKuudra;
}

export interface ModelsCropMilestone {
  level?: ModelsSkill;
  name?: string;
  texture?: string;
}

export interface ModelsCropUpgrade {
  level?: ModelsSkill;
  name?: string;
  texture?: string;
}

export type ModelsCrystalNucleusRunsCrystals = { [key: string]: string };

export type ModelsCrystalNucleusRunsParts = { [key: string]: string };

export interface ModelsCrystalNucleusRuns {
  crystals?: ModelsCrystalNucleusRunsCrystals;
  parts?: ModelsCrystalNucleusRunsParts;
}

export interface ModelsCrystalHollows {
  crystalHollowsLastAccess?: number;
  nucleusRuns?: number;
  progress?: ModelsCrystalNucleusRuns;
}

export interface ModelsMostDamageOutput {
  damage?: number;
  type?: string;
}

export interface ModelsDungeonFloorStats {
  best_score?: number;
  fastest_time?: number;
  fastest_time_s?: number;
  fastest_time_s_plus?: number;
  milestone_completions?: number;
  mobs_killed?: number;
  most_damage?: ModelsMostDamageOutput;
  most_healing?: number;
  most_mobs_killed?: number;
  tier_completions?: number;
  times_played?: number;
  watcher_kills?: number;
}

export interface ModelsSecretsOutput {
  found?: number;
  secretsPerRun?: number;
}

export interface ModelsDungeonStatsOutput {
  bloodMobKills?: number;
  highestFloorBeatenMaster?: number;
  highestFloorBeatenNormal?: number;
  secrets?: ModelsSecretsOutput;
}

export interface ModelsFormattedDungeonFloor {
  best_run?: ModelsBestRunOutput;
  name?: string;
  stats?: ModelsDungeonFloorStats;
  texture?: string;
}

export interface ModelsDungeonsOutput {
  catacombs?: ModelsFormattedDungeonFloor[];
  classes?: ModelsClassData;
  level?: ModelsSkill;
  master_catacombs?: ModelsFormattedDungeonFloor[];
  stats?: ModelsDungeonStatsOutput;
}

export type ModelsEmbedDataDungeonsClasses = { [key: string]: number };

export interface ModelsEmbedDataDungeons {
  classAverage?: number;
  classes?: ModelsEmbedDataDungeonsClasses;
  dungeoneering?: number;
}

export interface ModelsEmbedNetworth {
  nonCosmetic?: number;
  normal?: number;
}

export type ModelsEmbedDataSkillsSkills = { [key: string]: number };

export interface ModelsEmbedDataSkills {
  skillAverage?: number;
  skills?: ModelsEmbedDataSkillsSkills;
}

export type ModelsEmbedDataSlayersSlayers = { [key: string]: number };

export interface ModelsEmbedDataSlayers {
  slayers?: ModelsEmbedDataSlayersSlayers;
  xp?: number;
}

export interface ModelsEmbedData {
  bank?: number;
  displayName?: string;
  dungeons?: ModelsEmbedDataDungeons;
  game_mode?: string;
  joined?: number;
  networth?: ModelsEmbedNetworth;
  profile_cute_name?: string;
  profile_id?: string;
  purse?: number;
  skills?: ModelsEmbedDataSkills;
  skyblock_level?: number;
  slayers?: ModelsEmbedDataSlayers;
  username?: string;
  uuid?: string;
}

export interface ModelsEnchantingGame {
  attempts?: number;
  bestScore?: number;
  claims?: number;
  name?: string;
  texture?: string;
}

export interface ModelsEnchantingGameStats {
  bonusClicks?: number;
  games?: ModelsEnchantingGame[];
  lastAttempt?: number;
  lastClaimed?: number;
}

export interface ModelsEnchantingGameData {
  name?: string;
  stats?: ModelsEnchantingGameStats;
}

export type ModelsEnchantingOutputData = { [key: string]: ModelsEnchantingGameData };

export interface ModelsEnchantingOutput {
  data?: ModelsEnchantingOutputData;
  unlocked?: boolean;
}

export type ModelsEquipmentResultStats = { [key: string]: number };

export interface ModelsEquipmentResult {
  equipment?: ModelsStrippedItem[];
  stats?: ModelsEquipmentResultStats;
}

export interface ModelsFairySouls {
  found?: number;
  total?: number;
}

export type ModelsFarmingOutputContests = { [key: string]: ModelsContest };

export interface ModelsMedal {
  amount?: number;
  total?: number;
}

export type ModelsFarmingOutputMedals = { [key: string]: ModelsMedal };

export interface ModelsSkillToolsResult {
  highest_priority_tool?: ModelsStrippedItem;
  tools?: ModelsStrippedItem[];
}

export interface ModelsFarmingOutput {
  contests?: ModelsFarmingOutputContests;
  contestsAttended?: number;
  copper?: number;
  medals?: ModelsFarmingOutputMedals;
  pelts?: number;
  tools?: ModelsSkillToolsResult;
  uniqueGolds?: number;
}

export interface ModelsKill {
  amount?: number;
  id?: string;
  name?: string;
  texture?: string;
}

export interface ModelsTrophyFishProgress {
  caught?: number;
  tier?: string;
  total?: number;
}

export interface ModelsTrophyFishStage {
  name?: string;
  progress?: ModelsTrophyFishProgress[];
}

export interface ModelsTrophyFish {
  bronze?: number;
  description?: string;
  diamond?: number;
  gold?: number;
  id?: string;
  maxed?: boolean;
  name?: string;
  silver?: number;
  texture?: string;
}

export interface ModelsTrophyFishOutput {
  stage?: ModelsTrophyFishStage;
  totalCaught?: number;
  trophyFish?: ModelsTrophyFish[];
}

export interface ModelsFishingOuput {
  itemsFished?: number;
  kills?: ModelsKill[];
  seaCreaturesFished?: number;
  shredderBait?: number;
  shredderFished?: number;
  tools?: ModelsSkillToolsResult;
  treasure?: number;
  treasureLarge?: number;
  trophyFish?: ModelsTrophyFishOutput;
}

export interface ModelsForgeOutput {
  duration?: number;
  endingTime?: number;
  id?: string;
  name?: string;
  slot?: number;
  startingTime?: number;
}

export interface ModelsFossil {
  found?: boolean;
  name?: string;
  texture_path?: string;
}

export interface ModelsFossils {
  fossils?: ModelsFossil[];
  found?: number;
  max?: number;
}

export type ModelsGardenComposter = { [key: string]: number };

export interface SkycrypttypesRodPart {
  donated_museum?: boolean;
  part?: string;
}

export type SkycrypttypesExtraAttributesAttributes = { [key: string]: number };

export type SkycrypttypesExtraAttributesEnchantments = { [key: string]: number };

export type SkycrypttypesExtraAttributesGems = { [key: string]: unknown };

export type SkycrypttypesExtraAttributesRunes = { [key: string]: number };

/**
 * HideFlags       int             `nbt:"HideFlags" json:"HideFlags,omitempty"`
Unbreakable     int             `nbt:"Unbreakable" json:"Unbreakable,omitempty"`
Enchantments    []Enchantment   `nbt:"ench" json:"ench,omitempty"`
 */
export interface SkycrypttypesExtraAttributes {
  ability_scroll?: string[];
  additional_coins?: number;
  artOfPeaceApplied?: number;
  art_of_war_count?: number;
  attributes?: SkycrypttypesExtraAttributesAttributes;
  auction?: number;
  bid?: number;
  boosters?: string[];
  champion_combat_xp?: number;
  collected_coins?: number;
  compact_blocks?: number;
  divan_powder_coating?: number;
  donated_museum?: boolean;
  drill_part_engine?: string;
  drill_part_fuel_tank?: string;
  drill_part_upgrade_module?: string;
  dungeon_item_level?: unknown;
  dye_item?: string;
  edition?: number;
  enchantments?: SkycrypttypesExtraAttributesEnchantments;
  ethermerge?: number;
  expertise_kills?: number;
  farmed_cultivating?: number;
  farming_for_dummies_count?: number;
  gems?: SkycrypttypesExtraAttributesGems;
  hecatomb_s_runs?: number;
  hook?: SkycrypttypesRodPart;
  hot_potato_count?: number;
  id?: string;
  is_shiny?: boolean;
  item_tier?: number;
  jalapeno_count?: number;
  levelable_overclocks?: number;
  line?: SkycrypttypesRodPart;
  mana_disintegrator_count?: number;
  model?: string;
  modifier?: string;
  new_year_cake_bag_data?: number[];
  new_year_cake_bag_years?: number[];
  new_years_cake?: number;
  party_hat_color?: string;
  party_hat_emoji?: string;
  petInfo?: string;
  pickonimbus_durability?: number;
  polarvoid?: number;
  power_ability_scroll?: string;
  price?: number;
  rarity_upgrades?: number;
  runes?: SkycrypttypesExtraAttributesRunes;
  sack_pss?: number;
  sinker?: SkycrypttypesRodPart;
  skin?: string;
  talisman_enrichment?: string;
  thunder_charge?: number;
  timestamp?: unknown;
  tuned_transmission?: number;
  upgrade_level?: unknown;
  uuid?: string;
  winning_bid?: number;
  wood_singularity_count?: number;
}

export interface SkycrypttypesTexture {
  Signature?: string;
  Value?: string;
}

export interface SkycrypttypesProperties {
  textures?: SkycrypttypesTexture[];
}

export interface SkycrypttypesSkullOwner {
  Id?: string;
  Properties?: SkycrypttypesProperties;
}

export interface SkycrypttypesDisplay {
  Lore?: string[];
  Name?: string;
  color?: number;
}

export interface SkycrypttypesTag {
  ExtraAttributes?: SkycrypttypesExtraAttributes;
  SkullOwner?: SkycrypttypesSkullOwner;
  display?: SkycrypttypesDisplay;
}

export interface ModelsProcessedItem {
  Count?: number;
  Damage?: number;
  categories?: string[];
  containsItems?: ModelsProcessedItem[];
  display_name?: string;
  id?: string;
  isInactive?: boolean;
  lore?: string[];
  price?: number;
  rarity?: string;
  recombobulated?: boolean;
  shiny?: boolean;
  source?: string;
  tag?: SkycrypttypesTag;
  texture_pack?: string;
  texture_path?: string;
  wiki?: ModelsWikipediaLinks;
}

export interface ModelsPlotLayout {
  barnSkin?: string;
  layout?: ModelsProcessedItem[];
  total?: number;
  unlocked?: number;
}

export interface ModelsVisitorRarityData {
  completed?: number;
  maxUnique?: number;
  unique?: number;
  visited?: number;
}

export type ModelsVisitorsVisitors = { [key: string]: ModelsVisitorRarityData };

export interface ModelsVisitors {
  completed?: number;
  uniqueVisitors?: number;
  visited?: number;
  visitors?: ModelsVisitorsVisitors;
}

export interface ModelsGarden {
  composter?: ModelsGardenComposter;
  cropMilestones?: ModelsCropMilestone[];
  cropUpgrades?: ModelsCropUpgrade[];
  level?: ModelsSkill;
  plot?: ModelsPlotLayout;
  visitors?: ModelsVisitors;
}

export interface ModelsWeaponsResult {
  highest_priority_weapon?: ModelsStrippedItem;
  weapons?: ModelsStrippedItem[];
}

export interface ModelsGear {
  armor?: ModelsArmorResult;
  equipment?: ModelsEquipmentResult;
  wardrobe?: ModelsStrippedItem[][];
  weapons?: ModelsWeaponsResult;
}

export type ModelsGetMagicalPowerOutputHegemony = {
  amount?: number;
  rarity?: string;
};

export interface ModelsGetMagicalPowerRarities {
  [key: string]: {
    amount?: number;
    magicalPower?: number;
  };
}

export interface ModelsGetMagicalPowerOutput {
  abiphone?: number;
  accessories?: number;
  hegemony?: ModelsGetMagicalPowerOutputHegemony;
  rarities?: ModelsGetMagicalPowerRarities;
  riftPrism?: number;
  total?: number;
}

export type ModelsGetMissingAccessoresOutputEnrichments = { [key: string]: number };

export type ModelsGetMissingAccessoresOutputStats = { [key: string]: number };

export interface ModelsGetMissingAccessoresOutput {
  accessories?: ModelsStrippedItem[];
  enrichments?: ModelsGetMissingAccessoresOutputEnrichments;
  magicalPower?: ModelsGetMagicalPowerOutput;
  missing?: ModelsStrippedItem[];
  recombobulated?: number;
  selectedPower?: string;
  stats?: ModelsGetMissingAccessoresOutputStats;
  total?: number;
  totalRecombobulated?: number;
  unique?: number;
  upgrades?: ModelsStrippedItem[];
}

export interface ModelsGlaciteTunnels {
  corpses?: ModelsCorpses;
  fossilDust?: number;
  fossils?: ModelsFossils;
  mineshaftsEntered?: number;
}

export interface ModelsHotmTokens {
  available?: number;
  spent?: number;
  total?: number;
}

export interface ModelsMemberStats {
  cute_name?: string;
  profile_id?: string;
  removed?: boolean;
  username?: string;
  uuid?: string;
}

export interface ModelsPeakOfTheMountain {
  level?: number;
  max_level?: number;
}

export interface ModelsPowderAmount {
  available?: number;
  spent?: number;
  total?: number;
}

export interface ModelsPowderOutput {
  gemstone?: ModelsPowderAmount;
  glacite?: ModelsPowderAmount;
  mithril?: ModelsPowderAmount;
}

export interface ModelsMiningOutput {
  commissions?: ModelsCommissions;
  crystalHollows?: ModelsCrystalHollows;
  forge?: ModelsForgeOutput[];
  glaciteTunnels?: ModelsGlaciteTunnels;
  hotm?: ModelsProcessedItem[];
  level?: ModelsSkill;
  peakOfTheMountain?: ModelsPeakOfTheMountain;
  powder?: ModelsPowderOutput;
  selectedPickaxeAbility?: string;
  tokens?: ModelsHotmTokens;
  tools?: ModelsSkillToolsResult;
}

export interface ModelsMinion {
  maxTier?: number;
  name?: string;
  texture?: string;
  tiers?: number[];
}

export interface ModelsMinionCategory {
  maxedMinions?: number;
  maxedTiers?: number;
  minions?: ModelsMinion[];
  texture?: string;
  totalMinions?: number;
  totalTiers?: number;
}

export interface ModelsMinionSlotsOutput {
  bonusSlots?: number;
  current?: number;
  next?: number;
}

export type ModelsMinionsOutputMinions = { [key: string]: ModelsMinionCategory };

export interface ModelsMinionsOutput {
  maxedMinions?: number;
  maxedTiers?: number;
  minions?: ModelsMinionsOutputMinions;
  minionsSlots?: ModelsMinionSlotsOutput;
  totalMinions?: number;
  totalTiers?: number;
}

export type ModelsMiscAuctionsTotalBought = { [key: string]: number };

export type ModelsMiscAuctionsTotalSold = { [key: string]: number };

export interface ModelsMiscAuctions {
  bids?: number;
  created?: number;
  fees?: number;
  gold_earned?: number;
  gold_spent?: number;
  highest_bid?: number;
  no_bids?: number;
  total_bought?: ModelsMiscAuctionsTotalBought;
  total_sold?: ModelsMiscAuctionsTotalSold;
  won?: number;
}

export interface ModelsMiscDamage {
  highest_critical_damage?: number;
}

export type ModelsMiscDragonsDeaths = { [key: string]: number };

export type ModelsMiscDragonsFastestKill = { [key: string]: number };

export type ModelsMiscDragonsLastHits = { [key: string]: number };

export type ModelsMiscDragonsMostDamage = { [key: string]: number };

export interface ModelsMiscDragons {
  deaths?: ModelsMiscDragonsDeaths;
  ender_crystals_destroyed?: number;
  fastest_kill?: ModelsMiscDragonsFastestKill;
  last_hits?: ModelsMiscDragonsLastHits;
  most_damage?: ModelsMiscDragonsMostDamage;
}

export interface ModelsMiscEndstoneProtector {
  deaths?: number;
  kills?: number;
}

export interface ModelsMiscEssence {
  amount?: number;
  name?: string;
  texture?: string;
}

export interface ModelsMiscGifts {
  given?: number;
  received?: number;
}

export interface ModelsMiscKill {
  amount?: number;
  name?: string;
}

export interface ModelsMiscKills {
  deaths?: ModelsMiscKill[];
  kills?: ModelsMiscKill[];
  total_deaths?: number;
  total_kills?: number;
}

export type ModelsMiscMythologicalEventBurrowsChainsComplete = { [key: string]: number };

export type ModelsMiscMythologicalEventBurrowsDugCombat = { [key: string]: number };

export type ModelsMiscMythologicalEventBurrowsDugNext = { [key: string]: number };

export type ModelsMiscMythologicalEventBurrowsDugTreasure = { [key: string]: number };

export interface ModelsMiscMythologicalEvent {
  burrows_chains_complete?: ModelsMiscMythologicalEventBurrowsChainsComplete;
  burrows_dug_combat?: ModelsMiscMythologicalEventBurrowsDugCombat;
  burrows_dug_next?: ModelsMiscMythologicalEventBurrowsDugNext;
  burrows_dug_treasure?: ModelsMiscMythologicalEventBurrowsDugTreasure;
  kills?: number;
}

export type ModelsMiscOutputClaimedItems = { [key: string]: number };

export interface ModelsMiscPetMilestone {
  amount?: number;
  progress?: string;
  rarity?: string;
  total?: number;
}

export type ModelsMiscOutputPetMilestones = { [key: string]: ModelsMiscPetMilestone };

export type ModelsMiscOutputUncategorized = { [key: string]: unknown };

export interface ModelsMiscProfileUpgrades {
  [key: string]: number;
}

export interface ModelsMiscSeasonOfJerry {
  most_cannonballs_hit?: number;
  most_damage_dealt?: number;
  most_magma_damage_dealt?: number;
  most_snowballs_hit?: number;
}

export interface ModelsMiscOutput {
  auctions?: ModelsMiscAuctions;
  claimed_items?: ModelsMiscOutputClaimedItems;
  damage?: ModelsMiscDamage;
  dragons?: ModelsMiscDragons;
  endstone_protector?: ModelsMiscEndstoneProtector;
  essence?: ModelsMiscEssence[];
  gifts?: ModelsMiscGifts;
  kills?: ModelsMiscKills;
  mythological_event?: ModelsMiscMythologicalEvent;
  pet_milestones?: ModelsMiscOutputPetMilestones;
  profile_upgrades?: ModelsMiscProfileUpgrades;
  season_of_jerry?: ModelsMiscSeasonOfJerry;
  uncategorized?: ModelsMiscOutputUncategorized;
}

export interface SkycryptSrcModelsNetworthType {
  total?: number;
  unsoulboundTotal?: number;
}

export type SkycryptSrcModelsNetworthResultTypes = { [key: string]: SkycryptSrcModelsNetworthType };

export interface SkycryptSrcModelsNetworthResult {
  bank?: number;
  isNonCosmetic?: boolean;
  networth?: number;
  noInventory?: boolean;
  personalBank?: number;
  purse?: number;
  types?: SkycryptSrcModelsNetworthResultTypes;
  unsoulboundNetworth?: number;
}

export interface ModelsNetworth {
  nonCosmetic?: SkycryptSrcModelsNetworthResult;
  normal?: SkycryptSrcModelsNetworthResult;
}

export type ModelsStrippedPetStats = { [key: string]: number };

export interface ModelsStrippedPet {
  active?: boolean;
  display_name?: string;
  level?: number;
  lore?: string[];
  rarity?: string;
  stats?: ModelsStrippedPetStats;
  texture_path?: string;
  type?: string;
}

export interface ModelsPetScoreReward {
  bonus?: number;
  score?: number;
  unlocked?: boolean;
}

export type ModelsPetScoreStats = { [key: string]: number };

export interface ModelsPetScore {
  amount?: number;
  reward?: ModelsPetScoreReward[];
  stats?: ModelsPetScoreStats;
}

export interface ModelsOutputPets {
  amount?: number;
  amountSkins?: number;
  missing?: ModelsStrippedPet[];
  petScore?: ModelsPetScore;
  pets?: ModelsStrippedPet[];
  total?: number;
  totalCandyUsed?: number;
  totalPetExp?: number;
}

export interface ModelsPlayerResolve {
  displayName?: string;
  username?: string;
  uuid?: string;
}

export interface ModelsProcessingError {
  error?: string;
  message?: string;
  status?: string;
}

export interface ModelsProfilesStats {
  cute_name?: string;
  game_mode?: string;
  profile_id?: string;
  selected?: boolean;
}

export interface ModelsRankOutput {
  plusColor?: string;
  plusText?: string;
  rankColor?: string;
  rankText?: string;
}

export interface ModelsResourcePackConfig {
  author?: string;
  disabled?: boolean;
  icon?: string;
  id?: string;
  name?: string;
  url?: string;
  version?: string;
}

export interface ModelsRiftCastleOutput {
  grubberStacks?: number;
  maxBurgers?: number;
}

export interface ModelsRiftEnigmaOutput {
  souls?: number;
  totalSouls?: number;
}

export interface ModelsRiftMotesOutput {
  lifetime?: number;
  orbs?: number;
  purse?: number;
}

export interface ModelsRiftPorhtal {
  name?: string;
  texture?: string;
  unlocked?: boolean;
}

export interface ModelsRiftPortalsOutput {
  porhtals?: ModelsRiftPorhtal[];
  porhtalsFound?: number;
}

export interface ModelsRiftTimecharms {
  name?: string;
  texture?: string;
  unlocked?: boolean;
  unlockedAt?: number;
}

export interface ModelsRiftTimecharmsOutput {
  timecharms?: ModelsRiftTimecharms[];
  timecharmsFound?: number;
}

export interface ModelsRiftOutput {
  armor?: ModelsArmorResult;
  castle?: ModelsRiftCastleOutput;
  enigma?: ModelsRiftEnigmaOutput;
  equipment?: ModelsEquipmentResult;
  motes?: ModelsRiftMotesOutput;
  porhtal?: ModelsRiftPortalsOutput;
  timecharms?: ModelsRiftTimecharmsOutput;
  visits?: number;
}

export type ModelsSkillsSkills = { [key: string]: ModelsSkill };

export interface ModelsSkills {
  averageSkillLevel?: number;
  averageSkillLevelWithProgress?: number;
  skills?: ModelsSkillsSkills;
  totalSkillXp?: number;
}

export interface ModelsSkillsOutput {
  enchanting?: ModelsEnchantingOutput;
  farming?: ModelsFarmingOutput;
  fishing?: ModelsFishingOuput;
  mining?: ModelsMiningOutput;
}

export type ModelsSlayerDataKills = { [key: string]: number };

export interface ModelsSlayerLevel {
  level?: number;
  maxLevel?: number;
  maxed?: boolean;
  xp?: number;
  xpForNext?: number;
}

export interface ModelsSlayerData {
  kills?: ModelsSlayerDataKills;
  level?: ModelsSlayerLevel;
  name?: string;
  texture?: string;
}

export type ModelsSlayersOutputData = { [key: string]: ModelsSlayerData };

export type ModelsSlayersOutputStats = { [key: string]: number };

export interface ModelsSlayersOutput {
  data?: ModelsSlayersOutputData;
  stats?: ModelsSlayersOutputStats;
  totalSlayerExp?: number;
}

export interface ModelsStatsInfo {
  [key: string]: number;
}

export type ModelsStatsStats = { [key: string]: ModelsStatsInfo };

export interface ModelsStats {
  stats?: ModelsStatsStats;
}

export type ModelsStatsOutputApiSettings = { [key: string]: boolean };

export interface SkycrypttypesSocialMediaLinks {
  DISCORD?: string;
  HYPIXEL?: string;
  TWITCH?: string;
  TWITTER?: string;
}

export interface ModelsStatsOutput {
  apiSettings?: ModelsStatsOutputApiSettings;
  bank?: number;
  displayName?: string;
  fairySouls?: ModelsFairySouls;
  game_mode?: string;
  joined?: number;
  members?: ModelsMemberStats[];
  personalBank?: number;
  profile_cute_name?: string;
  profile_id?: string;
  profiles?: ModelsProfilesStats[];
  purse?: number;
  rank?: ModelsRankOutput;
  selected?: boolean;
  skills?: ModelsSkills;
  skyblock_level?: ModelsSkill;
  social?: SkycrypttypesSocialMediaLinks;
  username?: string;
  uuid?: string;
}

export interface SkycrypttypesItem {
  Count?: number;
  Damage?: number;
  containsItems?: SkycrypttypesItem[];
  id?: number;
  price?: number;
  tag?: SkycrypttypesTag;
}

export type GetApiEmbedUuidParams = {
  /**
   * Profile ID (optional, defaults to selected profile)
   */
  profileId?: string;
};

export type GetApiEmojis200 = { [key: string]: unknown };

export type GetApiInventoryUuidProfileIdInventoryIdParams = {
  /**
   * Search query (required when inventoryId is 'search')
   */
  query?: string;
};

/**
 * Returns accessories for the given user and profile ID
 * @summary Get accessories stats of a specified player
 */
export type getApiAccessoriesUuidProfileIdResponse200 = {
  data: ModelsGetMissingAccessoresOutput;
  status: 200;
};

export type getApiAccessoriesUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiAccessoriesUuidProfileIdResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getApiAccessoriesUuidProfileIdResponseSuccess = getApiAccessoriesUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiAccessoriesUuidProfileIdResponseError = (getApiAccessoriesUuidProfileIdResponse400 | getApiAccessoriesUuidProfileIdResponse500) & {
  headers: Headers;
};

export type getApiAccessoriesUuidProfileIdResponse = getApiAccessoriesUuidProfileIdResponseSuccess | getApiAccessoriesUuidProfileIdResponseError;

export const getGetApiAccessoriesUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/accessories/${uuid}/${profileId}`;
};

export const getApiAccessoriesUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiAccessoriesUuidProfileIdResponse> => {
  return customFetch<getApiAccessoriesUuidProfileIdResponse>(getGetApiAccessoriesUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns bestiary for the given user and profile ID
 * @summary Get bestiary stats of a specified player
 */
export type getApiBestiaryUuidProfileIdResponse200 = {
  data: ModelsBestiaryOutput;
  status: 200;
};

export type getApiBestiaryUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiBestiaryUuidProfileIdResponseSuccess = getApiBestiaryUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiBestiaryUuidProfileIdResponseError = getApiBestiaryUuidProfileIdResponse400 & {
  headers: Headers;
};

export type getApiBestiaryUuidProfileIdResponse = getApiBestiaryUuidProfileIdResponseSuccess | getApiBestiaryUuidProfileIdResponseError;

export const getGetApiBestiaryUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/bestiary/${uuid}/${profileId}`;
};

export const getApiBestiaryUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiBestiaryUuidProfileIdResponse> => {
  return customFetch<getApiBestiaryUuidProfileIdResponse>(getGetApiBestiaryUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns collections for the given user and profile ID
 * @summary Get collections stats of a specified player
 */
export type getApiCollectionsUuidProfileIdResponse200 = {
  data: ModelsCollectionsOutput;
  status: 200;
};

export type getApiCollectionsUuidProfileIdResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getApiCollectionsUuidProfileIdResponseSuccess = getApiCollectionsUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiCollectionsUuidProfileIdResponseError = getApiCollectionsUuidProfileIdResponse500 & {
  headers: Headers;
};

export type getApiCollectionsUuidProfileIdResponse = getApiCollectionsUuidProfileIdResponseSuccess | getApiCollectionsUuidProfileIdResponseError;

export const getGetApiCollectionsUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/collections/${uuid}/${profileId}`;
};

export const getApiCollectionsUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiCollectionsUuidProfileIdResponse> => {
  return customFetch<getApiCollectionsUuidProfileIdResponse>(getGetApiCollectionsUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns Crimson Isle stats for the given user and profile ID
 * @summary Get Crimson Isle stats of a specified player
 */
export type getApiCrimsonIsleUuidProfileIdResponse200 = {
  data: ModelsCrimsonIsleOutput;
  status: 200;
};

export type getApiCrimsonIsleUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiCrimsonIsleUuidProfileIdResponseSuccess = getApiCrimsonIsleUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiCrimsonIsleUuidProfileIdResponseError = getApiCrimsonIsleUuidProfileIdResponse400 & {
  headers: Headers;
};

export type getApiCrimsonIsleUuidProfileIdResponse = getApiCrimsonIsleUuidProfileIdResponseSuccess | getApiCrimsonIsleUuidProfileIdResponseError;

export const getGetApiCrimsonIsleUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/crimson_isle/${uuid}/${profileId}`;
};

export const getApiCrimsonIsleUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiCrimsonIsleUuidProfileIdResponse> => {
  return customFetch<getApiCrimsonIsleUuidProfileIdResponse>(getGetApiCrimsonIsleUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns dungeons for the given user and profile ID
 * @summary Get dungeons stats of a specified player
 */
export type getApiDungeonsUuidProfileIdResponse200 = {
  data: ModelsDungeonsOutput;
  status: 200;
};

export type getApiDungeonsUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiDungeonsUuidProfileIdResponseSuccess = getApiDungeonsUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiDungeonsUuidProfileIdResponseError = getApiDungeonsUuidProfileIdResponse400 & {
  headers: Headers;
};

export type getApiDungeonsUuidProfileIdResponse = getApiDungeonsUuidProfileIdResponseSuccess | getApiDungeonsUuidProfileIdResponseError;

export const getGetApiDungeonsUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/dungeons/${uuid}/${profileId}`;
};

export const getApiDungeonsUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiDungeonsUuidProfileIdResponse> => {
  return customFetch<getApiDungeonsUuidProfileIdResponse>(getGetApiDungeonsUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns embed data for the given user (UUID or username) and optional profile ID
 * @summary Get embed data for a specified player
 */
export type getApiEmbedUuidResponse200 = {
  data: ModelsEmbedData;
  status: 200;
};

export type getApiEmbedUuidResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiEmbedUuidResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getApiEmbedUuidResponseSuccess = getApiEmbedUuidResponse200 & {
  headers: Headers;
};
export type getApiEmbedUuidResponseError = (getApiEmbedUuidResponse400 | getApiEmbedUuidResponse500) & {
  headers: Headers;
};

export type getApiEmbedUuidResponse = getApiEmbedUuidResponseSuccess | getApiEmbedUuidResponseError;

export const getGetApiEmbedUuidUrl = (uuid: string, params?: GetApiEmbedUuidParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/embed/${uuid}?${stringifiedParams}` : `/api/embed/${uuid}`;
};

export const getApiEmbedUuid = async (uuid: string, params?: GetApiEmbedUuidParams, options?: RequestInit): Promise<getApiEmbedUuidResponse> => {
  return customFetch<getApiEmbedUuidResponse>(getGetApiEmbedUuidUrl(uuid, params), {
    ...options,
    method: "GET"
  });
};

/**
 * Retrieves all emojis from the database
 * @summary Get all emojis
 */
export type getApiEmojisResponse200 = {
  data: GetApiEmojis200;
  status: 200;
};

export type getApiEmojisResponse500 = {
  data: FiberMap;
  status: 500;
};

export type getApiEmojisResponseSuccess = getApiEmojisResponse200 & {
  headers: Headers;
};
export type getApiEmojisResponseError = getApiEmojisResponse500 & {
  headers: Headers;
};

export type getApiEmojisResponse = getApiEmojisResponseSuccess | getApiEmojisResponseError;

export const getGetApiEmojisUrl = () => {
  return `/api/emojis`;
};

export const getApiEmojis = async (options?: RequestInit): Promise<getApiEmojisResponse> => {
  return customFetch<getApiEmojisResponse>(getGetApiEmojisUrl(), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns garden data for the given profile ID
 * @summary Get garden stats of a specified profile
 */
export type getApiGardenProfileIdResponse200 = {
  data: ModelsGarden;
  status: 200;
};

export type getApiGardenProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiGardenProfileIdResponseSuccess = getApiGardenProfileIdResponse200 & {
  headers: Headers;
};
export type getApiGardenProfileIdResponseError = getApiGardenProfileIdResponse400 & {
  headers: Headers;
};

export type getApiGardenProfileIdResponse = getApiGardenProfileIdResponseSuccess | getApiGardenProfileIdResponseError;

export const getGetApiGardenProfileIdUrl = (profileId: string) => {
  return `/api/garden/${profileId}`;
};

export const getApiGardenProfileId = async (profileId: string, options?: RequestInit): Promise<getApiGardenProfileIdResponse> => {
  return customFetch<getApiGardenProfileIdResponse>(getGetApiGardenProfileIdUrl(profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns gear for the given user and profile ID
 * @summary Get gear stats of a specified player
 */
export type getApiGearUuidProfileIdResponse200 = {
  data: ModelsGear;
  status: 200;
};

export type getApiGearUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiGearUuidProfileIdResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getApiGearUuidProfileIdResponseSuccess = getApiGearUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiGearUuidProfileIdResponseError = (getApiGearUuidProfileIdResponse400 | getApiGearUuidProfileIdResponse500) & {
  headers: Headers;
};

export type getApiGearUuidProfileIdResponse = getApiGearUuidProfileIdResponseSuccess | getApiGearUuidProfileIdResponseError;

export const getGetApiGearUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/gear/${uuid}/${profileId}`;
};

export const getApiGearUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiGearUuidProfileIdResponse> => {
  return customFetch<getApiGearUuidProfileIdResponse>(getGetApiGearUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns a PNG image of a head for the given texture ID
 * @summary Render and return a head image
 */
export type getApiHeadTextureIdResponse200ApplicationJson = {
  data: unknown;
  status: 200;
};

export type getApiHeadTextureIdResponse200ImagePng = {
  data: Blob;
  status: 200;
};

export type getApiHeadTextureIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiHeadTextureIdResponse500 = {
  data: string;
  status: 500;
};

export type getApiHeadTextureIdResponseSuccess = (getApiHeadTextureIdResponse200ApplicationJson | getApiHeadTextureIdResponse200ImagePng) & {
  headers: Headers;
};
export type getApiHeadTextureIdResponseError = (getApiHeadTextureIdResponse400 | getApiHeadTextureIdResponse500) & {
  headers: Headers;
};

export type getApiHeadTextureIdResponse = getApiHeadTextureIdResponseSuccess | getApiHeadTextureIdResponseError;

export const getGetApiHeadTextureIdUrl = (textureId: string) => {
  return `/api/head/${textureId}`;
};

export const getApiHeadTextureId = async (textureId: string, options?: RequestInit): Promise<getApiHeadTextureIdResponse> => {
  return customFetch<getApiHeadTextureIdResponse>(getGetApiHeadTextureIdUrl(textureId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns inventory items for the given user, profile ID, and inventory ID. Supports museum, search, and other inventories.
 * @summary Get inventory items for a specified player
 */
export type getApiInventoryUuidProfileIdInventoryIdResponse200 = {
  data: ModelsStrippedItem[];
  status: 200;
};

export type getApiInventoryUuidProfileIdInventoryIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiInventoryUuidProfileIdInventoryIdResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getApiInventoryUuidProfileIdInventoryIdResponseSuccess = getApiInventoryUuidProfileIdInventoryIdResponse200 & {
  headers: Headers;
};
export type getApiInventoryUuidProfileIdInventoryIdResponseError = (getApiInventoryUuidProfileIdInventoryIdResponse400 | getApiInventoryUuidProfileIdInventoryIdResponse500) & {
  headers: Headers;
};

export type getApiInventoryUuidProfileIdInventoryIdResponse = getApiInventoryUuidProfileIdInventoryIdResponseSuccess | getApiInventoryUuidProfileIdInventoryIdResponseError;

export const getGetApiInventoryUuidProfileIdInventoryIdUrl = (uuid: string, profileId: string, inventoryId: string, params?: GetApiInventoryUuidProfileIdInventoryIdParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/inventory/${uuid}/${profileId}/${inventoryId}?${stringifiedParams}` : `/api/inventory/${uuid}/${profileId}/${inventoryId}`;
};

export const getApiInventoryUuidProfileIdInventoryId = async (uuid: string, profileId: string, inventoryId: string, params?: GetApiInventoryUuidProfileIdInventoryIdParams, options?: RequestInit): Promise<getApiInventoryUuidProfileIdInventoryIdResponse> => {
  return customFetch<getApiInventoryUuidProfileIdInventoryIdResponse>(getGetApiInventoryUuidProfileIdInventoryIdUrl(uuid, profileId, inventoryId, params), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns a PNG image of an item for the given texture ID
 * @summary Render and return an item image
 */
export type getApiItemItemIdResponse200ApplicationJson = {
  data: unknown;
  status: 200;
};

export type getApiItemItemIdResponse200ImagePng = {
  data: Blob;
  status: 200;
};

export type getApiItemItemIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiItemItemIdResponse500 = {
  data: string;
  status: 500;
};

export type getApiItemItemIdResponseSuccess = (getApiItemItemIdResponse200ApplicationJson | getApiItemItemIdResponse200ImagePng) & {
  headers: Headers;
};
export type getApiItemItemIdResponseError = (getApiItemItemIdResponse400 | getApiItemItemIdResponse500) & {
  headers: Headers;
};

export type getApiItemItemIdResponse = getApiItemItemIdResponseSuccess | getApiItemItemIdResponseError;

export const getGetApiItemItemIdUrl = (itemId: string) => {
  return `/api/item/${itemId}`;
};

export const getApiItemItemId = async (itemId: string, options?: RequestInit): Promise<getApiItemItemIdResponse> => {
  return customFetch<getApiItemItemIdResponse>(getGetApiItemItemIdUrl(itemId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns a PNG image of leather armor for the given type and color
 * @summary Render and return a leather armor image
 */
export type getApiLeatherTypeColorResponse200ApplicationJson = {
  data: unknown;
  status: 200;
};

export type getApiLeatherTypeColorResponse200ImagePng = {
  data: Blob;
  status: 200;
};

export type getApiLeatherTypeColorResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiLeatherTypeColorResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getApiLeatherTypeColorResponseSuccess = (getApiLeatherTypeColorResponse200ApplicationJson | getApiLeatherTypeColorResponse200ImagePng) & {
  headers: Headers;
};
export type getApiLeatherTypeColorResponseError = (getApiLeatherTypeColorResponse400 | getApiLeatherTypeColorResponse500) & {
  headers: Headers;
};

export type getApiLeatherTypeColorResponse = getApiLeatherTypeColorResponseSuccess | getApiLeatherTypeColorResponseError;

export const getGetApiLeatherTypeColorUrl = (type: string, color: string) => {
  return `/api/leather/${type}/${color}`;
};

export const getApiLeatherTypeColor = async (type: string, color: string, options?: RequestInit): Promise<getApiLeatherTypeColorResponse> => {
  return customFetch<getApiLeatherTypeColorResponse>(getGetApiLeatherTypeColorUrl(type, color), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns minions for the given user and profile ID
 * @summary Get minions stats of a specified player
 */
export type getApiMinionsUuidProfileIdResponse200 = {
  data: ModelsMinionsOutput;
  status: 200;
};

export type getApiMinionsUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiMinionsUuidProfileIdResponseSuccess = getApiMinionsUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiMinionsUuidProfileIdResponseError = getApiMinionsUuidProfileIdResponse400 & {
  headers: Headers;
};

export type getApiMinionsUuidProfileIdResponse = getApiMinionsUuidProfileIdResponseSuccess | getApiMinionsUuidProfileIdResponseError;

export const getGetApiMinionsUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/minions/${uuid}/${profileId}`;
};

export const getApiMinionsUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiMinionsUuidProfileIdResponse> => {
  return customFetch<getApiMinionsUuidProfileIdResponse>(getGetApiMinionsUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns misc stats for the given user and profile ID
 * @summary Get misc stats of a specified player
 */
export type getApiMiscUuidProfileIdResponse200 = {
  data: ModelsMiscOutput;
  status: 200;
};

export type getApiMiscUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiMiscUuidProfileIdResponseSuccess = getApiMiscUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiMiscUuidProfileIdResponseError = getApiMiscUuidProfileIdResponse400 & {
  headers: Headers;
};

export type getApiMiscUuidProfileIdResponse = getApiMiscUuidProfileIdResponseSuccess | getApiMiscUuidProfileIdResponseError;

export const getGetApiMiscUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/misc/${uuid}/${profileId}`;
};

export const getApiMiscUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiMiscUuidProfileIdResponse> => {
  return customFetch<getApiMiscUuidProfileIdResponse>(getGetApiMiscUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns networth for the given user and profile ID
 * @summary Get networth of a specified player
 */
export type getApiNetworthUuidProfileIdResponse200 = {
  data: ModelsNetworth;
  status: 200;
};

export type getApiNetworthUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiNetworthUuidProfileIdResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getApiNetworthUuidProfileIdResponseSuccess = getApiNetworthUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiNetworthUuidProfileIdResponseError = (getApiNetworthUuidProfileIdResponse400 | getApiNetworthUuidProfileIdResponse500) & {
  headers: Headers;
};

export type getApiNetworthUuidProfileIdResponse = getApiNetworthUuidProfileIdResponseSuccess | getApiNetworthUuidProfileIdResponseError;

export const getGetApiNetworthUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/networth/${uuid}/${profileId}`;
};

export const getApiNetworthUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiNetworthUuidProfileIdResponse> => {
  return customFetch<getApiNetworthUuidProfileIdResponse>(getGetApiNetworthUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns pets for the given user and profile ID
 * @summary Get pets stats of a specified player
 */
export type getApiPetsUuidProfileIdResponse200 = {
  data: ModelsOutputPets;
  status: 200;
};

export type getApiPetsUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiPetsUuidProfileIdResponseSuccess = getApiPetsUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiPetsUuidProfileIdResponseError = getApiPetsUuidProfileIdResponse400 & {
  headers: Headers;
};

export type getApiPetsUuidProfileIdResponse = getApiPetsUuidProfileIdResponseSuccess | getApiPetsUuidProfileIdResponseError;

export const getGetApiPetsUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/pets/${uuid}/${profileId}`;
};

export const getApiPetsUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiPetsUuidProfileIdResponse> => {
  return customFetch<getApiPetsUuidProfileIdResponse>(getGetApiPetsUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns player stats for the given user and profile ID
 * @summary Get player stats of a specified player
 */
export type getApiPlayerStatsUuidProfileIdResponse200 = {
  data: ModelsStats;
  status: 200;
};

export type getApiPlayerStatsUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiPlayerStatsUuidProfileIdResponseSuccess = getApiPlayerStatsUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiPlayerStatsUuidProfileIdResponseError = getApiPlayerStatsUuidProfileIdResponse400 & {
  headers: Headers;
};

export type getApiPlayerStatsUuidProfileIdResponse = getApiPlayerStatsUuidProfileIdResponseSuccess | getApiPlayerStatsUuidProfileIdResponseError;

export const getGetApiPlayerStatsUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/playerStats/${uuid}/${profileId}`;
};

export const getApiPlayerStatsUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiPlayerStatsUuidProfileIdResponse> => {
  return customFetch<getApiPlayerStatsUuidProfileIdResponse>(getGetApiPlayerStatsUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns a PNG image of a potion for the given type and color
 * @summary Render and return a potion image
 */
export type getApiPotionTypeColorResponse200ApplicationJson = {
  data: unknown;
  status: 200;
};

export type getApiPotionTypeColorResponse200ImagePng = {
  data: Blob;
  status: 200;
};

export type getApiPotionTypeColorResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiPotionTypeColorResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getApiPotionTypeColorResponseSuccess = (getApiPotionTypeColorResponse200ApplicationJson | getApiPotionTypeColorResponse200ImagePng) & {
  headers: Headers;
};
export type getApiPotionTypeColorResponseError = (getApiPotionTypeColorResponse400 | getApiPotionTypeColorResponse500) & {
  headers: Headers;
};

export type getApiPotionTypeColorResponse = getApiPotionTypeColorResponseSuccess | getApiPotionTypeColorResponseError;

export const getGetApiPotionTypeColorUrl = (type: string, color: string) => {
  return `/api/potion/${type}/${color}`;
};

export const getApiPotionTypeColor = async (type: string, color: string, options?: RequestInit): Promise<getApiPotionTypeColorResponse> => {
  return customFetch<getApiPotionTypeColorResponse>(getGetApiPotionTypeColorUrl(type, color), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns a list of resource packs
 * @summary Get list of resource packs
 */
export type getApiResourcepacksResponse200 = {
  data: ModelsResourcePackConfig[];
  status: 200;
};

export type getApiResourcepacksResponseSuccess = getApiResourcepacksResponse200 & {
  headers: Headers;
};
export type getApiResourcepacksResponse = getApiResourcepacksResponseSuccess;

export const getGetApiResourcepacksUrl = () => {
  return `/api/resourcepacks`;
};

export const getApiResourcepacks = async (options?: RequestInit): Promise<getApiResourcepacksResponse> => {
  return customFetch<getApiResourcepacksResponse>(getGetApiResourcepacksUrl(), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns rift data for the given user and profile ID
 * @summary Get rift stats of a specified player
 */
export type getApiRiftUuidProfileIdResponse200 = {
  data: ModelsRiftOutput;
  status: 200;
};

export type getApiRiftUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiRiftUuidProfileIdResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getApiRiftUuidProfileIdResponseSuccess = getApiRiftUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiRiftUuidProfileIdResponseError = (getApiRiftUuidProfileIdResponse400 | getApiRiftUuidProfileIdResponse500) & {
  headers: Headers;
};

export type getApiRiftUuidProfileIdResponse = getApiRiftUuidProfileIdResponseSuccess | getApiRiftUuidProfileIdResponseError;

export const getGetApiRiftUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/rift/${uuid}/${profileId}`;
};

export const getApiRiftUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiRiftUuidProfileIdResponse> => {
  return customFetch<getApiRiftUuidProfileIdResponse>(getGetApiRiftUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns skills for the given user and profile ID
 * @summary Get skills stats of a specified player
 */
export type getApiSkillsUuidProfileIdResponse200 = {
  data: ModelsSkillsOutput;
  status: 200;
};

export type getApiSkillsUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiSkillsUuidProfileIdResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getApiSkillsUuidProfileIdResponseSuccess = getApiSkillsUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiSkillsUuidProfileIdResponseError = (getApiSkillsUuidProfileIdResponse400 | getApiSkillsUuidProfileIdResponse500) & {
  headers: Headers;
};

export type getApiSkillsUuidProfileIdResponse = getApiSkillsUuidProfileIdResponseSuccess | getApiSkillsUuidProfileIdResponseError;

export const getGetApiSkillsUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/skills/${uuid}/${profileId}`;
};

export const getApiSkillsUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiSkillsUuidProfileIdResponse> => {
  return customFetch<getApiSkillsUuidProfileIdResponse>(getGetApiSkillsUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns slayer statistics for the given user and profile ID
 * @summary Get slayer stats of a specified player
 */
export type getApiSlayerUuidProfileIdResponse200 = {
  data: ModelsSlayersOutput;
  status: 200;
};

export type getApiSlayerUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiSlayerUuidProfileIdResponseSuccess = getApiSlayerUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiSlayerUuidProfileIdResponseError = getApiSlayerUuidProfileIdResponse400 & {
  headers: Headers;
};

export type getApiSlayerUuidProfileIdResponse = getApiSlayerUuidProfileIdResponseSuccess | getApiSlayerUuidProfileIdResponseError;

export const getGetApiSlayerUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/slayer/${uuid}/${profileId}`;
};

export const getApiSlayerUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiSlayerUuidProfileIdResponse> => {
  return customFetch<getApiSlayerUuidProfileIdResponse>(getGetApiSlayerUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns stats for the given user and profile ID
 * @summary Get stats of a specified player
 */
export type getApiStatsUuidProfileIdResponse200 = {
  data: ModelsStatsOutput;
  status: 200;
};

export type getApiStatsUuidProfileIdResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiStatsUuidProfileIdResponse500 = {
  data: ModelsProcessingError;
  status: 500;
};

export type getApiStatsUuidProfileIdResponseSuccess = getApiStatsUuidProfileIdResponse200 & {
  headers: Headers;
};
export type getApiStatsUuidProfileIdResponseError = (getApiStatsUuidProfileIdResponse400 | getApiStatsUuidProfileIdResponse500) & {
  headers: Headers;
};

export type getApiStatsUuidProfileIdResponse = getApiStatsUuidProfileIdResponseSuccess | getApiStatsUuidProfileIdResponseError;

export const getGetApiStatsUuidProfileIdUrl = (uuid: string, profileId: string) => {
  return `/api/stats/${uuid}/${profileId}`;
};

export const getApiStatsUuidProfileId = async (uuid: string, profileId: string, options?: RequestInit): Promise<getApiStatsUuidProfileIdResponse> => {
  return customFetch<getApiStatsUuidProfileIdResponse>(getGetApiStatsUuidProfileIdUrl(uuid, profileId), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns the username associated with the given UUID
 * @summary Get username for a specified UUID
 */
export type getApiUsernameUuidResponse200 = {
  data: ModelsPlayerResolve;
  status: 200;
};

export type getApiUsernameUuidResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiUsernameUuidResponseSuccess = getApiUsernameUuidResponse200 & {
  headers: Headers;
};
export type getApiUsernameUuidResponseError = getApiUsernameUuidResponse400 & {
  headers: Headers;
};

export type getApiUsernameUuidResponse = getApiUsernameUuidResponseSuccess | getApiUsernameUuidResponseError;

export const getGetApiUsernameUuidUrl = (uuid: string) => {
  return `/api/username/${uuid}`;
};

export const getApiUsernameUuid = async (uuid: string, options?: RequestInit): Promise<getApiUsernameUuidResponse> => {
  return customFetch<getApiUsernameUuidResponse>(getGetApiUsernameUuidUrl(uuid), {
    ...options,
    method: "GET"
  });
};

/**
 * Returns the UUID associated with the given username
 * @summary Get UUID for a specified username
 */
export type getApiUuidUsernameResponse200 = {
  data: ModelsPlayerResolve;
  status: 200;
};

export type getApiUuidUsernameResponse400 = {
  data: ModelsProcessingError;
  status: 400;
};

export type getApiUuidUsernameResponseSuccess = getApiUuidUsernameResponse200 & {
  headers: Headers;
};
export type getApiUuidUsernameResponseError = getApiUuidUsernameResponse400 & {
  headers: Headers;
};

export type getApiUuidUsernameResponse = getApiUuidUsernameResponseSuccess | getApiUuidUsernameResponseError;

export const getGetApiUuidUsernameUrl = (username: string) => {
  return `/api/uuid/${username}`;
};

export const getApiUuidUsername = async (username: string, options?: RequestInit): Promise<getApiUuidUsernameResponse> => {
  return customFetch<getApiUuidUsernameResponse>(getGetApiUuidUsernameUrl(username), {
    ...options,
    method: "GET"
  });
};
