import type { APISettings, AccessoriesOutput, BestiaryStats, Collections, CrimsonIsle, DungeonsStats, Enchanting, Farming, Fishing, Items, MainStats, MiningStats, Minions, Misc, Pets, Rank, Rift, Skill, Skills, SlayerData } from "./global";
export * from "./processed/profile/api_settings";
export * from "./processed/profile/bestiary";
export * from "./processed/profile/collections";
export * from "./processed/profile/crimson_isle";
export * from "./processed/profile/dungeons";
export * from "./processed/profile/enchanting";
export * from "./processed/profile/farming";
export * from "./processed/profile/fishing";
export * from "./processed/profile/items";
export * from "./processed/profile/main_stats";
export * from "./processed/profile/mining";
export * from "./processed/profile/minions";
export * from "./processed/profile/misc";
export * from "./processed/profile/pet-stats";
export * from "./processed/profile/pets";
export * from "./processed/profile/rank";
export * from "./processed/profile/rift";
export * from "./processed/profile/skills";
export * from "./processed/profile/slayer";

export type Stats = {
  displayName: string;
  username: string;
  uuid: string;
  profile_id: string;
  profile_cute_name: string;
  game_mode: string;
  selected: boolean;
  members: { uuid: string; username: string }[];
  skills: Skills | null;
  rank: Rank | undefined;
  social: Record<string, string>;
  profiles: { profile_id: string; cute_name: string; game_mode: string; selected: boolean }[] | null;
  skyblock_level: Skill | null;
  stats: MainStats | null;
  items: Items | null;
  accessories: AccessoriesOutput | null;
  pets: Pets | null;
  mining: MiningStats | null;
  farming: Farming | null;
  enchanting: Enchanting | null;
  fishing: Fishing;
  slayer: SlayerData | null;
  dungeons: DungeonsStats | null;
  minions: Minions | null;
  bestiary: BestiaryStats | null;
  collections: Collections | null;
  crimson_isle: CrimsonIsle | null;
  rift: Rift | null;
  misc: Misc | null;
  errors: Record<string, string>;
  apiSettings: APISettings;
};

export type ValidStats = {
  displayName: string;
  username: string;
  uuid: string;
  profile_id: string;
  profile_cute_name: string;
  game_mode: string;
  selected: boolean;
  members: { uuid: string; username: string; removed: boolean }[];
  skills: Skills;
  rank: Rank | undefined;
  social: Record<string, string>;
  profiles: { profile_id: string; cute_name: string; game_mode: string; selected: boolean }[];
  skyblock_level: Skill;
  stats: MainStats;
  items: Items;
  accessories: AccessoriesOutput;
  pets: Pets;
  mining: MiningStats;
  farming: Farming;
  enchanting: Enchanting;
  fishing: Fishing;
  slayer: SlayerData;
  dungeons: DungeonsStats;
  minions: Minions;
  bestiary: BestiaryStats;
  collections: Collections;
  crimson_isle: CrimsonIsle;
  rift: Rift;
  misc: Misc;
  apiSettings: APISettings;
  errors: Record<string, string>;
};
