name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checks:
    if: github.event.pull_request.head.repo.fork == true
    uses: ./.github/workflows/checks.yml

  tests:
    if: github.event.pull_request.head.repo.fork == true
    uses: ./.github/workflows/test.yml

  build:
    if: github.event.pull_request.head.repo.fork == true
    uses: ./.github/workflows/build.yml
