name: Website

on:
  push:
    paths: ["src/**", "Dockerfile", ".github/workflows/website.yml"]
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    if: |
      (github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/dev')
      && github.repository_owner == 'SkyCryptWebsite'
      && github.event_name != 'pull_request'

    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  formatting-checks:
    name: Check linting (es-lint), formatting (prettier), and svelte checks (svelte-check)
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: PNPM Install
        uses: ./.github/actions/pnpm-install

      - name: Make dummy env for types
        run: |
          echo "ls -a ."
          ls -a .
          mv .env.example .env

      - name: Check linting, formatting, and svelte checks
        run: pnpm lint

  build:
    name: Vite Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Clone NotEnoughUpdates-REPO
        uses: actions/checkout@v4
        with:
          repository: NotEnoughUpdates/NotEnoughUpdates-REPO
          path: NotEnoughUpdates-REPO/
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: PNPM Install
        uses: ./.github/actions/pnpm-install

      - name: Make dummy env for types
        run: |
          echo "ls -a ."
          ls -a .
          mv .env.example .env

      - name: Vite Build
        run: pnpm run build

  package:
    name: Package into Container
    runs-on: ubuntu-latest
    needs: [analyze, formatting-checks, build]
    if: |
      (github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/dev')
      && github.repository_owner == 'SkyCryptWebsite'
      && github.event_name != 'pull_request'

    permissions:
      packages: write
      contents: read

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
